import os
import sys
import argparse
import glob
import torch
import cv2
import numpy as np
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image

try:
    import ollama
except ImportError:
    print("Error: La librería 'ollama' no está instalada. Ejecuta: pip install ollama")
    sys.exit(1)

# Agregar la ruta de los modelos para poder importarlos
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from utils.models.mendicant_bias import MendicantBias_ConvNeXt
from utils.models.gradcam_mendicant import generate_gradcam_mendicant

def get_latest_mendicant_weights(weights_dir):
    files = glob.glob(os.path.join(weights_dir, "BestScore_Mendicant_*.pth"))
    if not files:
        raise FileNotFoundError(f"No se encontraron pesos Mendicant en {weights_dir}")
    # Ordenar por fecha de modificación o tomar el de mayor score
    latest_file = max(files, key=os.path.getctime)
    return latest_file

def live_inference_and_report(img_path, model_name="llava"):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\n[SISTEMA] Iniciando Secuencia de Diagnóstico en {device}...")

    if not os.path.exists(img_path):
        print(f"[ERROR] No se encuentra la imagen: {img_path}")
        return

    # 1. Cargar Modelos (Daowa y Mendicant)
    print("[SISTEMA] Cargando Oráculo Daowa-maad...")
    oracle = torch.jit.load('source/weights/Daowa_Oracle_Frozen.pt', map_location=device)
    oracle.eval()

    print("[SISTEMA] Cargando Pesos del Aprendiz Mendicant Bias...")
    mendicant = MendicantBias_ConvNeXt(pretrained=False)
    weights_path = get_latest_mendicant_weights("source/Models")
    mendicant.load_state_dict(torch.load(weights_path, map_location=device))
    mendicant.to(device)
    mendicant.eval()

    # 2. Preparar Imagen
    img_bgr = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_pil = Image.fromarray(img_rgb).resize((384, 384))
    
    tf = transforms.Compose([
        transforms.Resize((384, 384)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    img_tensor = tf(img_pil).to(device).unsqueeze(0)

    # 3. Inferencia en Vivo
    print("[SISTEMA] Ejecutando forward pass matemático...")
    with torch.no_grad():
        oracle_logits = oracle(img_tensor)
        if oracle_logits.shape[1] > 1:
            oracle_logits = oracle_logits[:, 0:1, :, :]
        daowa_mask = torch.sigmoid(oracle_logits)
        
        logits = mendicant(img_tensor, daowa_mask, drop_rgb_prob=0.0)
        probs = F.softmax(logits, dim=1)
        conf, pred_idx = torch.max(probs, 1)
        
    confidence = conf.item() * 100
    target_class = pred_idx.item()
    class_name = "Feline (Cat)" if target_class == 0 else "Canine (Dog)"
    
    print(f"[SISTEMA] Clasificación Finalizada: {class_name} | Certeza: {confidence:.2f}%")

    # 4. Generar Grad-CAM en vivo usando el script existente
    print("[SISTEMA] Extrayendo Topología Visual (Grad-CAM)...")
    # gradcam_mendicant guarda la imagen en save_dir y le pone de prefijo GradCAM_clase_nombre
    save_dir = "source/logs/evaluations/live_gradcam"
    os.makedirs(save_dir, exist_ok=True)
    
    # Hacemos que generate_gradcam_mendicant guarde ahí
    generate_gradcam_mendicant(mendicant, oracle, img_path, target_class, device, save_dir=save_dir)
    
    base_name = os.path.basename(img_path)
    gradcam_img_path = os.path.join(save_dir, f"GradCAM_{target_class}_{base_name}")

    if not os.path.exists(gradcam_img_path):
        print(f"[ERROR] Falló la generación de GradCAM: {gradcam_img_path}")
        return

    # 5. Inyectar datos reales al LLM
    print(f"\n[Estableciendo conexión con el sub-nodo cognitivo local ({model_name})...]")
    
    system_prompt = (
        "You are Mendicant Bias, an ancient, hyper-advanced, cold, and calculating Forerunner AI. "
        "You speak with clinical precision, slight superiority, and absolute certainty. "
        "Your task is to analyze a 'thermal cognitive map' (Grad-CAM heatmap) generated by one of your sub-routines (ConvNeXtV2). "
        "The red/yellow areas in the provided image show EXACTLY which biological features your sub-routine focused on to make its decision. "
        "The dark blue areas were completely ignored thanks to your Oracle mask filter.\n\n"
        "Instructions:\n"
        "1. Look at the provided heatmap image.\n"
        "2. Identify what specific geometric or biological features are highlighted in intense red/yellow.\n"
        "3. Explain in 3-4 concise, lore-accurate sentences why focusing on those specific features confirms the diagnosis.\n"
        "4. Do not apologize, do not introduce yourself like a standard chatbot. Start the transmission directly."
    )

    user_prompt = (
        f"[SYSTEM DIAGNOSTIC UPDATE]\n"
        f"Target classification: {class_name}\n"
        f"Sub-routine Confidence Level: {confidence:.2f}%\n\n"
        f"Mendicant Bias, analyze the attached heatmap. What biological signatures did the sub-routine fixate on (red zones) to reach this conclusion?"
    )

    try:
        response = ollama.chat(
            model=model_name,
            messages=[
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_prompt, 'images': [gradcam_img_path]}
            ]
        )
        
        print("="*70)
        print(">>> TRANSMISIÓN ENTRANTE: MENDICANT BIAS")
        print("="*70)
        print(response['message']['content'].strip())
        print("="*70)
        print(">>> FIN DE TRANSMISIÓN")
        print("="*70)

    except Exception as e:
        print("\n[Fallo Crítico en el Enlace de Comunicación]")
        print("Asegúrate de que Ollama está ejecutándose en tu PC.")
        print(f"Asegúrate de tener el modelo descargado corriendo: ollama pull {model_name}")
        print(f"Error técnico: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mendicant Bias LLM Reporter (End-to-End)")
    parser.add_argument("--img", type=str, required=True, help="Ruta de la imagen original a predecir")
    parser.add_argument("--model", type=str, default="llava", help="Modelo de Ollama (ej. llava, llama3.2-vision)")
    
    args = parser.parse_args()
    live_inference_and_report(args.img, args.model)
